<a href="https://colab.research.google.com/github/alirezash97/Advanced-AI-Course/blob/main/FirstProject/DLS_updated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
class Stack:
     def __init__(self):
         self.items = []

     def isEmpty(self):
         return self.items == []

     def push(self, item):
         self.items.append(item)

     def pop(self):
         return self.items.pop()

     def peek(self):
         return self.items[len(self.items)-1]

     def size(self):
         return len(self.items)
     
     def len(self):
         return len(self.items)


In [5]:
# Crossing Rivers Problem with DLS
import numpy as np

# Initianization # passed = 1 or not = 0
# last index = boat flag ==> 0 for behind the river and 1 for crossed from the river

dls_stack = Stack()
start_state = np.zeros((1, 10))



In [6]:
import itertools 
  
def findsubsets(s, n): 
    return list(itertools.combinations(s, n)) 


In [91]:
def IsValid(state):
  

  
  
  validation_flag = True
  state = np.squeeze(state)
  

  for node in Expanded_nodes:
    node = np.squeeze(node)      
    if (node[:-2] == state[:-2]).all() :
      validation_flag = False


  ######## 

  # thief can not be alone with family
  if state[0] == 0 and state[1] == 1:
    if np.sum(state[1:8]) != 6 :
      validation_flag = False
  elif state[0] == 1 and state[1] == 0:
    if np.sum(state[1:8]) != 0 :
      validation_flag = False

  # father witth sons and mother with daughters
  elif state[2] == 0 and state[3] == 1:
    if state[6] == 0 or state[7] == 0 or state[4] == 1 or state[5] == 1:
      validation_flag = False
  elif state[2] == 1 and state[3] == 0:
    if state[6] == 1 or state[7] == 1 or state[4] == 0 or state[5] == 0:
      validation_flag = False

  




#   ##########

#   # if thief is in passengers then police should ride the boat
#   if  ( (0 in passengers) and (1 not in passengers) ) :
#     validation_flag = False

# #####################
#   elif (state[2] == 0) and ( (state[3] in passengers)):
#     if (state[6] == 0) or (state[7] == 0):
#      validation_flag = False

#   elif (state[3] == 0) and ( (state[2] in passengers)):
#     if (state[4] == 0) or (state[5] == 0):
#      validation_flag = False
# #####################
  
#   # don't let thief be alone with family
#   elif (state[0] == 0) and (0 not in passengers) and (1 in passengers) and (state[-2] == 0):
#     if (((state[2] == 0) and (2 not in passengers)) or ((state[3] == 0) and (3 not in passengers))
#      or ((state[4] == 0) and (4 not in passengers)) or ((state[5] == 0) and (5 not in passengers))):
#      validation_flag = False
  
#   # don't let thief be alone with family
#   elif (state[0] == 1) and (0 not in passengers) and (1 in passengers) and (state[-2] == 1):
#     if (((state[2] == 1) and (2 not in passengers)) or ((state[3] == 1) and (3 not in passengers))
#      or ((state[4] == 1) and (4 not in passengers)) or ((state[5] == 1) and (5 not in passengers))):
#      validation_flag = False
  
#   # father with sons and mother with daughters
#   elif ( ((2 in passengers) and (6 in passengers)) or ((2 in passengers) and (7 in passengers)) 
#    or ((3 in passengers) and (4 in passengers)) or ((3 in passengers) and (5 in passengers))):
#    validation_flag = False
  
#   # police, father and mother can ride the boat
#   elif ( (1 not in passengers) and (2 not in passengers) and (3 not in passengers) ):
#     validation_flag = False
  
#   else:
#     pass


  return validation_flag





In [92]:
def operator(state, dls_stack):


  
  flag = state[-2]
  my_state = state[:-2]
  not_passed_indices = np.where(my_state == 0)[0] 
  passed_indices = np.where(my_state == 1)[0]


  if flag == 0:
      
    boat_with_two_passengers = findsubsets(not_passed_indices, 2)
    boat_with_one_passenger = findsubsets(not_passed_indices, 1)
    boat_passengers = boat_with_two_passengers + boat_with_one_passenger


    for i in boat_passengers:
      
      if (1 in i) or (2 in i) or (3 in i): 

     
        offspring = np.zeros((1, 10))
        offspring[0][:-2] = state[:-2]
        
          # passengers getting on the boat
        for j in i:
          offspring[0][j] = 1
          # tigger boat position
        offspring[0][-2] = int(not flag)
          # increase the level 
        offspring[0][-1] = int(state[-1] + 1)
          # push the offspring
        dls_stack.push(offspring)


      else:
        pass

  else:

    boat_with_two_passengers = findsubsets(passed_indices, 2)
    boat_with_one_passenger = findsubsets(passed_indices, 1)
    boat_passengers = boat_with_two_passengers + boat_with_one_passenger

    for i in boat_passengers:

      if (1 in i) or (2 in i) or (3 in i): 

        offspring = np.zeros((1, 10))
        offspring[0][:-2] = state[:-2]
          
          # passengers getting on the boat (he comes back)
        for j in i:
          offspring[0][j] = 0
          # tigger boat position
        offspring[0][-2] = int(not flag)
          # increase the level 
        offspring[0][-1] = int(state[-1] + 1)
          
          # push the offspring
        
        dls_stack.push(offspring)


      else:
        pass

  return dls_stack


In [93]:

final_state = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [97]:
import copy


def dls(start_state, final_state, dls_stack, limit):

  #########
  global matrix_path
  matrix_path = np.zeros((limit+1, 10))
  ########


  dls_stack = operator(start_state[0], dls_stack)
  solved = False


  
  while not solved:

    
    if dls_stack.len() != 0:
      
      global Expanded_nodes
      Expanded_nodes = []
      current_state = dls_stack.pop()
      Expanded_nodes.append(current_state)
      

      state_level = int(current_state[0][-1]) -1
      print(current_state)
      matrix_path[state_level+1, :] = np.array(current_state)
      
      if IsValid(current_state):
        # it does not matter when these two match
        if np.array_equal(current_state[0][:-1], final_state[:-1]):
          print(matrix_path)
          solved = True
          print("Done!")
          print("Guide: [Thief, Police, Father, Mother, Son1, Son2, Daughter1, Daughter2, Boat Flag ( 0 ==> behind, 1 ==> crossed ), State Level]") 
        
        elif current_state[0][-1] < limit:

          dls_stack = operator(current_state[0], dls_stack)
          
          
          
        
        else:
          pass
      

      else:
        pass

       
    else:
      print("the limit is not enough!")
      break


dls(start_state, final_state, dls_stack, 18)


[[0. 0. 0. 1. 0. 0. 0. 0. 1. 1.]]
[[0. 0. 1. 0. 0. 0. 0. 0. 1. 1.]]
[[0. 1. 0. 0. 0. 0. 0. 0. 1. 1.]]
[[0. 0. 0. 1. 0. 0. 0. 1. 1. 1.]]
[[0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]]
[[0. 0. 0. 1. 0. 1. 0. 0. 1. 1.]]
[[0. 0. 0. 1. 1. 0. 0. 0. 1. 1.]]
[[0. 0. 1. 0. 0. 0. 0. 1. 1. 1.]]
[[0. 0. 1. 0. 0. 0. 1. 0. 1. 1.]]
[[0. 0. 1. 0. 0. 1. 0. 0. 1. 1.]]
[[0. 0. 1. 0. 1. 0. 0. 0. 1. 1.]]
[[0. 0. 1. 1. 0. 0. 0. 0. 1. 1.]]
[[0. 1. 0. 0. 0. 0. 0. 1. 1. 1.]]
[[0. 1. 0. 0. 0. 0. 1. 0. 1. 1.]]
[[0. 1. 0. 0. 0. 1. 0. 0. 1. 1.]]
[[0. 1. 0. 0. 1. 0. 0. 0. 1. 1.]]
[[0. 1. 0. 1. 0. 0. 0. 0. 1. 1.]]
[[0. 1. 1. 0. 0. 0. 0. 0. 1. 1.]]
[[1. 0. 0. 1. 0. 0. 0. 0. 1. 1.]]
[[1. 0. 1. 0. 0. 0. 0. 0. 1. 1.]]
[[1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]]
[[ 1.  1.  0.  0.  0.  0.  0.  1.  1. 49.]]


IndexError: ignored