<a href="https://colab.research.google.com/github/alirezash97/Advanced-AI-Course/blob/main/DLS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
class Stack:
     def __init__(self):
         self.items = []

     def isEmpty(self):
         return self.items == []

     def push(self, item):
         self.items.append(item)

     def pop(self):
         return self.items.pop()

     def peek(self):
         return self.items[len(self.items)-1]

     def size(self):
         return len(self.items)
     
     def len(self):
         return len(self.items)


In [2]:
# Crossing Rivers Problem with DLS
import numpy as np

# Initianization # passed = 1 or not = 0
# last index = boat flag ==> 0 for behind the river and 1 for crossed from the river

dls_stack = Stack()
start_state = np.zeros((1, 10))



In [4]:
import itertools 
  
def findsubsets(s, n): 
    return list(itertools.combinations(s, n)) 


In [5]:
def validation(state, passengers):
  
  
  validation_flag = True

  # if thief is in passengers then police should ride the boat
  if  ( (0 in passengers) and (1 not in passengers) ) :
    validation_flag = False
  
  # don't let thief be alone with family
  elif (state[0] == 0) and (0 not in passengers) and (1 in passengers) and (state[-2] == 0):
    if (((state[2] == 0) and (2 not in passengers)) or ((state[3] == 0) and (3 not in passengers))
     or ((state[4] == 0) and (4 not in passengers)) or ((state[5] == 0) and (5 not in passengers))):
     validation_flag = False
  
  # don't let thief be alone with family
  elif (state[0] == 1) and (0 not in passengers) and (1 in passengers) and (state[-2] == 1):
    if (((state[2] == 1) and (2 not in passengers)) or ((state[3] == 1) and (3 not in passengers))
     or ((state[4] == 1) and (4 not in passengers)) or ((state[5] == 1) and (5 not in passengers))):
     validation_flag = False
  
  # father with sons and mother with daughters
  elif ( ((2 in passengers) and (6 in passengers)) or ((2 in passengers) and (7 in passengers)) 
   or ((3 in passengers) and (4 in passengers)) or ((3 in passengers) and (5 in passengers))):
   validation_flag = False
  
  # police, father and mother can ride the boat
  elif ( (1 not in passengers) and (2 not in passengers) and (3 not in passengers) ):
    validation_flag = False
  
  else:
    pass


  return validation_flag

# m_state = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
# passengers = np.array([0, 3])
# validation(m_state, passengers)



In [6]:
def operator(state, dls_stack):


  
  flag = state[-2]
  my_state = state[:-2]
  not_passed_indices = np.where(my_state == 0)[0] 
  passed_indices = np.where(my_state == 1)[0]


  if flag == 0:
      
    boat_with_two_passengers = findsubsets(not_passed_indices, 2)
    boat_with_one_passenger = findsubsets(not_passed_indices, 1)
    boat_passengers = boat_with_two_passengers + boat_with_one_passenger

    for i in boat_passengers:


      valid = validation(state, i)
      if valid:
        offspring = np.zeros((1, 10))
        offspring[0][:-2] = state[:-2]
       
        # passengers getting on the boat
        for j in i:
          offspring[0][j] = 1
        # tigger boat position
        offspring[0][-2] = int(not flag)
        # increase the level 
        offspring[0][-1] = int(state[-1] + 1)
        # push the offspring
        dls_stack.push(offspring)

      else:
        pass

  else:

    boat_with_two_passengers = findsubsets(passed_indices, 2)
    boat_with_one_passenger = findsubsets(passed_indices, 1)
    boat_passengers = boat_with_two_passengers + boat_with_one_passenger

    for i in boat_passengers:

      valid = validation(state, i)
      if valid:
        offspring = np.zeros((1, 10))
        offspring[0][:-2] = state[:-2]
        
        # passengers getting on the boat (he comes back)
        for j in i:
          offspring[0][j] = 0
        # tigger boat position
        offspring[0][-2] = int(not flag)
        # increase the level 
        offspring[0][-1] = int(state[-1] + 1)
        # push the offspring
        dls_stack.push(offspring)
      else:
        pass

  return dls_stack


In [7]:
# state = np.array([0., 0., 0., 1., 1., 0., 0., 1., 1., 3.])
# for i in range ((new_stack.len())):
#   new_stack.pop()
# new_stack = operator(state, dls_stack)

In [33]:


# Initianization # passed = 1 or not = 0
# last index = boat flag ==> 0 for behind the river and 1 for crossed from the river



# The thief did not passsed
final_state = np.array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [36]:
import copy


def dls(start_state, final_state, dls_stack, limit):

  dls_stack = operator(start_state[0], dls_stack)
  solved = False


  #########
  matrix_path = np.zeros((limit+1, 10))
  ########

  while not solved:

    if dls_stack.len() != 0:
      
      current_state = dls_stack.pop()

      state_level = int(current_state[0][-1]) -1
      matrix_path[state_level+1, :] = np.array(current_state)
      
      #######################
      # print(path)
      # for item in path:
        
      #   if item[0][-1] >= current_state[0][-1]:
      #     print(item[0])
      #     print(current_state[0])
      #     print('yes')

      #     path.remove(np.array(item[0]).all())
      #######################

      
      # path.append(current_state)

      
      # it does not matter when these two match
      
      
      if np.array_equal(current_state[0][:-1], final_state[:-1]):
        print(matrix_path)
        solved = True
        print("Done!")
        print("Guide: [Thief, Police, Father, Mother, Son1, Son2, Daughter1, Daughter2, Boat Flag ( 0 ==> behind, 1 ==> crossed ), State Level]") 
      
      elif current_state[0][-1] < limit:

        dls_stack = operator(current_state[0], dls_stack)
        
        
        
      
      else:
        pass

    
    else:
      print("the limit is not enough!")
      break


dls(start_state, final_state, dls_stack, 11)


[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  2.]
 [ 0.  0.  0.  1.  0.  0.  1.  1.  1.  3.]
 [ 0.  0.  0.  0.  0.  0.  1.  1.  0.  4.]
 [ 0.  0.  1.  0.  0.  1.  1.  1.  1.  5.]
 [ 0.  0.  0.  0.  0.  1.  1.  1.  0.  6.]
 [ 0.  0.  1.  0.  1.  1.  1.  1.  1.  7.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  0.  8.]
 [ 0.  0.  1.  1.  1.  1.  1.  1.  1.  9.]
 [ 0.  0.  1.  0.  1.  1.  1.  1.  0. 10.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1. 11.]]
Done!
Guide: [Thief, Police, Father, Mother, Son1, Son2, Daughter1, Daughter2, Boat Flag ( 0 ==> behind, 1 ==> crossed ), State Level]
