<a href="https://colab.research.google.com/github/alirezash97/Advanced-AI-Course/blob/main/DLS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [100]:
class Stack:
     def __init__(self):
         self.items = []

     def isEmpty(self):
         return self.items == []

     def push(self, item):
         self.items.append(item)

     def pop(self):
         return self.items.pop()

     def peek(self):
         return self.items[len(self.items)-1]

     def size(self):
         return len(self.items)
     
     def len(self):
         return len(self.items)


In [ ]:
solved = False

In [101]:
# Crossing Rivers Problem with DLS
import numpy as np


# Initianization # passed = 1 or not = 0
# last index = boat flag ==> 0 for behind the river and 1 for crossed from the river
passed = np.zeros((1, 9))
dls_stack = Stack()
start_state = np.zeros((1, 10))
current_state = np.zeros((1, 10))

# The thief did not passsed
final_stated = np.array([0, 1, 1, 1, 1, 1, 1, 1, 1])



In [23]:
[T, P, F, M, S1, S2, D1, D2, Flag, Level]
[1, 1, 0, 0, 0, 0, 1, 1, 1, 8]

array([2, 3, 4, 5])

In [15]:
np.random.randint(8, size=(1, 2))

array([[5, 7]])

In [26]:
a = 0
int(not a)

1

In [35]:
import random
a = np.array([4, 6, 2, 9, 2])

b = random.sample(set(a), 2)
b[0]

2

In [34]:
temp_offspring = np.zeros((1, 9))
temp_offspring[0][-1]

0.0

In [102]:
import itertools 
  
def findsubsets(s, n): 
    return list(itertools.combinations(s, n)) 

array = np.array([1, 5, 6, 3])
a = findsubsets(array, 2)
b = findsubsets(array, 1)
c = a + b
c[9]

(3,)

In [118]:
def validation(state, passengers):
  
  
  validation_flag = True

  # if thief is in passengers then police should ride the boat
  if  ( (0 in passengers) and (1 not in passengers) ) :
    validation_flag = False
  
  # don't let thief be alone with family
  elif (state[0] == 0) and (0 not in passengers) and (1 in passengers) and (state[-2] == 0):
    if (((state[2] == 0) and (2 not in passengers)) or ((state[3] == 0) and (3 not in passengers))
     or ((state[4] == 0) and (4 not in passengers)) or ((state[5] == 0) and (5 not in passengers))):
     validation_flag = False
  
  # don't let thief be alone with family
  elif (state[0] == 1) and (0 not in passengers) and (1 in passengers) and (state[-2] == 1):
    if (((state[2] == 1) and (2 not in passengers)) or ((state[3] == 1) and (3 not in passengers))
     or ((state[4] == 1) and (4 not in passengers)) or ((state[5] == 1) and (5 not in passengers))):
     validation_flag = False
  
  # father with sons and mother with daughters
  elif ( ((2 in passengers) and (6 in passengers)) or ((2 in passengers) and (7 in passengers)) 
   or ((3 in passengers) and (4 in passengers)) or ((3 in passengers) and (5 in passengers))):
   validation_flag = False
  
  # police, father and mother can ride the boat
  elif ( (1 not in passengers) and (2 not in passengers) and (3 not in passengers) ):
    validation_flag = False
  
  else:
    pass


  return validation_flag

m_state = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
passengers = np.array([0, 3])
validation(m_state, passengers)



False

In [119]:
def operator(state, dls_stack):


  
  flag = state[-2]
  my_state = state[:-2]
  not_passed_indices = np.where(my_state == 0)[0] 
  passed_indices = np.where(my_state == 1)[0]


  if flag == 0:
      
    boat_with_two_passengers = findsubsets(not_passed_indices, 2)
    boat_with_one_passenger = findsubsets(not_passed_indices, 1)
    boat_passengers = boat_with_two_passengers + boat_with_one_passenger

    for i in boat_passengers:

      print(i)
      valid = validation(state, i)
      if valid:
        print("valid")
        offspring = np.zeros((1, 10))
        offspring[0][:-2] = state[:-2]
       
        # passengers getting on the boat
        for j in i:
          offspring[0][j] = 1
        # tigger boat position
        offspring[0][-2] = int(not flag)
        # increase the level 
        offspring[0][-1] = int(state[-1] + 1)
        # push the offspring
        dls_stack.push(offspring)
        print("pushed")
      else:
        pass

  else:

    boat_with_two_passengers = findsubsets(passed_indices, 2)
    boat_with_one_passenger = findsubsets(passed_indices, 1)
    boat_passengers = boat_with_two_passengers + boat_with_one_passenger

    for i in boat_passengers:

      print(state)
      print(i)

      valid = validation(state, i)
      if valid:
        print("valid")
        offspring = np.zeros((1, 10))
        offspring[0][:-2] = state[:-2]
        
        # passengers getting on the boat (he comes back)
        for j in i:
          offspring[0][j] = 0
        # tigger boat position
        offspring[0][-2] = int(not flag)
        # increase the level 
        offspring[0][-1] = int(state[-1] + 1)
        # push the offspring
        dls_stack.push(offspring)
        print("pushed")
      else:
        pass

  return dls_stack


In [153]:
state = np.array([0., 0., 0., 0., 1., 0., 0., 0., 0., 2.])
for i in range (new_stack.len()):
  new_stack.pop()
new_stack = operator(state, dls_stack)

(0, 1)
valid
pushed
(0, 2)
(0, 3)
(0, 5)
(0, 6)
(0, 7)
(1, 2)
(1, 3)
(1, 5)
(1, 6)
(1, 7)
(2, 3)
valid
pushed
(2, 5)
valid
pushed
(2, 6)
(2, 7)
(3, 5)
(3, 6)
valid
pushed
(3, 7)
valid
pushed
(5, 6)
(5, 7)
(6, 7)
(0,)
(1,)
(2,)
valid
pushed
(3,)
valid
pushed
(5,)
(6,)
(7,)


In [154]:
new_stack.len()

7

In [151]:
new_stack.pop()

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 2.]])

In [152]:
new_stack.pop()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 2.]])

In [143]:
new_stack.pop()

array([[0., 0., 0., 1., 0., 0., 0., 1., 1., 1.]])

In [144]:
new_stack.pop()

array([[0., 0., 0., 1., 0., 0., 1., 0., 1., 1.]])

In [145]:
new_stack.pop()

array([[0., 0., 1., 0., 0., 1., 0., 0., 1., 1.]])

In [146]:
new_stack.pop()

array([[0., 0., 1., 0., 1., 0., 0., 0., 1., 1.]])

In [147]:
new_stack.pop()

array([[0., 0., 1., 1., 0., 0., 0., 0., 1., 1.]])

In [148]:
new_stack.pop()

array([[1., 1., 0., 0., 0., 0., 0., 0., 1., 1.]])